In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Step 1: Reading Data

In [3]:
data = pd.read_csv('data.csv')

In [4]:
data.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177.0,3,low,F,44,1233.0,1
1,2,F,Flight,4,5,216.0,2,low,M,59,3088.0,1
2,3,A,Flight,2,2,183.0,4,low,M,48,3374.0,1
3,4,B,Flight,3,3,176.0,4,medium,M,10,1177.0,1
4,5,C,Flight,2,2,184.0,3,medium,F,46,2484.0,1

In [5]:
data.describe()

,ID,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
count,10999.00000,10999.000000,10999.000000,10901.000000,10999.000000,10999.000000,10860.000000,10999.000000
mean,5500.00000,4.054459,2.990545,210.194386,3.567597,13.373216,3641.667035,0.596691
std,3175.28214,1.141490,1.413603,48.063598,1.522860,16.205527,1635.078989,0.490584
min,1.00000,2.000000,1.000000,96.000000,2.000000,1.000000,1001.000000,0.000000
25%,2750.50000,3.000000,2.000000,169.000000,3.000000,4.000000,1843.500000,0.000000
50%,5500.00000,4.000000,3.000000,214.000000,3.000000,7.000000,4157.500000,1.000000
75%,8249.50000,5.000000,4.000000,251.000000,4.000000,10.000000,5058.250000,1.000000
max,10999.00000,7.000000,5.000000,310.000000,10.000000,65.000000,7684.000000,1.000000