In [30]:
import pandas as pd
from scipy import stats

In [31]:
df = pd.read_csv("AB_testing_data.csv")

In [32]:
df.head()

   Day   Conversion fraction A  Conversion fraction B
0     1                   0.15                   0.19
1     2                   0.12                   0.20
2     3                   0.18                   0.18
3     4                   0.19                   0.22
4     5                   0.17                   0.25

In [33]:
df.loc[:,['Conversion fraction A', 'Conversion fraction B']].describe()

       Conversion fraction A  Conversion fraction B
count              35.000000              35.000000
mean                0.161429               0.191429
std                 0.034822               0.031729
min                 0.110000               0.110000
25%                 0.130000               0.175000
50%                 0.160000               0.190000
75%                 0.185000               0.200000
max                 0.230000               0.270000

Here mean of conversion fraction of B is more than that of A.
Shall we assume B is better than A?
</br>
No, we shall perform two sample t test to establish the statistical significance.

### Two sample t-test with equal varaiance

H0: Two samples are same, any difference is purely by chance.

In [34]:
sample_1 = df['Conversion fraction A']
sample_2 = df['Conversion fraction B']

In [35]:
eq_var = True

In [36]:
stat, p = stats.ttest_ind(sample_1, sample_2, equal_var=eq_var)
print(f"t-test statistic: {stat}")
print(f"p-value: {p}")
print(f"{'H0 Rejected' if p < 0.05 else 'H0 Accepted'}")

t-test statistic: -3.7674244936575474
p-value: 0.00034704350989135126
H0 Rejected