In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("market_baskets_data.csv")

In [3]:
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,whole wheat pasta,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,soup,light cream,shallot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,frozen vegetables,spaghetti,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

In [5]:
#[a,b,c]
#[e,f]
#[a,e,f,k,l ....j]

In [6]:
len(data.columns)

20

In [7]:
# Lets get the data in the form of lists of lists for the apriori algorithm
baskets = [[str(data.values[i, j]) for j in range(0, 20) if str(data.values[i, j])!='nan'] for i in range(0, len(data))]

In [8]:
#overall_data - should be list
# within list - a list each for every basket

In [9]:
type(baskets)

list

In [10]:
len(baskets)

7501

In [11]:
baskets[0]

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [12]:
baskets[1]

['burgers', 'meatballs', 'eggs']

In [13]:
from apyori import apriori # pip install apyori ( Go to Anaconda Prompt)
help(apriori)

Help on function apriori in module apyori:

apriori(transactions, **kwargs)
    Executes Apriori algorithm and returns a RelationRecord generator.

    Arguments:
        transactions -- A transaction iterable object
                        (eg. [['A', 'B'], ['B', 'C']]).

    Keyword arguments:
        min_support -- The minimum support of relations (float).
        min_confidence -- The minimum confidence of relations (float).
        min_lift -- The minimum lift of relations (float).
        max_length -- The maximum length of the relation (integer).

In [14]:
rules = apriori(baskets, min_support=0.01, min_confidence=0.25, min_lift=2)
result = list(rules)

In [15]:
result

[RelationRecord(items=frozenset({'herb & pepper', 'frozen pizza'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'frozen pizza'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'frozen pizza', 'spaghetti'}), support=0.03919477403012932, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen pizza'}), items_add=frozenset({'spaghetti'}), confidence=0.3989145183175034, lift=2.291162176033379)]),
 RelationRecord(items=frozenset({'soup', 'milk'}), support=0.015197973603519531, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'milk'}), confidence=0.3007915567282322, lift=2.3212319619531585)]),
 RelationRecord(items=frozenset({'red wine', 'spaghetti'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine'}), items_add=frozenset({'spaghetti'}), confidence=0.36492890995260663, lift=2.095966120638976)]),
 RelationRecord(items=frozenset({'chocolate', 'mineral water', 'milk'}), support=0.013998133582189041, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate', 'mineral water'}), items_add=frozenset({'milk'}), confidence=0.26582278481012656, lift=2.0513752148773245)]),
 RelationRecord(items=frozenset({'chocolate', 'spaghetti', 'milk'}), support=0.010931875749900012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate', 'spaghetti'}), items_add=frozenset({'milk'}), confidence=0.2789115646258503, lift=2.152382352117802)]),
 RelationRecord(items=frozenset({'frozen pizza', 'mineral water', 'eggs'}), support=0.010131982402346354, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen pizza', 'eggs'}), items_add=frozenset({'mineral water'}), confidence=0.5066666666666667, lift=2.125563012677107)]),
 RelationRecord(items=frozenset({'frozen pizza', 'mineral water', 'milk'}), support=0.011065191307825623, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen pizza', 'milk'}), items_add=frozenset({'mineral water'}), confidence=0.503030303030303, lift=2.1103077757440176), OrderedStatistic(items_base=frozenset({'frozen pizza', 'mineral water'}), items_add=frozenset({'milk'}), confidence=0.2703583061889251, lift=2.0863761879867564)]),
 RelationRecord(items=frozenset({'frozen pizza', 'spaghetti', 'mineral water'}), support=0.017064391414478068, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen pizza', 'mineral water'}), items_add=frozenset({'spaghetti'}), confidence=0.41693811074918563, lift=2.3946805273580716), OrderedStatistic(items_base=frozenset({'mineral water', 'spaghetti'}), items_add=frozenset({'frozen pizza'}), confidence=0.2857142857142857, lift=2.90792789300252)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'mineral water', 'milk'}), support=0.011065191307825623, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'mineral water'}), items_add=frozenset({'milk'}), confidence=0.3097014925373134, lift=2.3899906332534853)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti', 'milk'}), support=0.01573123583522197, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'spaghetti'}), items_add=frozenset({'milk'}), confidence=0.26339285714285715, lift=2.032623273074662)]),
 RelationRecord(items=frozenset({'olive oil', 'mineral water', 'spaghetti'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil', 'mineral water'}), items_add=frozenset({'spaghetti'}), confidence=0.3719806763285024, lift=2.13646788142427)])]

In [16]:
# Frozen set is just an immutable version of a Python set object.
# While elements of a set can be modified at any time, elements of the frozen set remain the same after creation. 
# Due to this, frozen sets can be used as keys in Dictionary or as elements of another set.
result[0]

RelationRecord(items=frozenset({'herb & pepper', 'frozen pizza'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'frozen pizza'}), confidence=0.3234501347708895, lift=3.2919938411349285)])

In [17]:
print("Number of rules found with given thresholds :", len(result))

Number of rules found with given thresholds : 12

In [18]:

items_rules = result[0]
items_rules

RelationRecord(items=frozenset({'herb & pepper', 'frozen pizza'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'frozen pizza'}), confidence=0.3234501347708895, lift=3.2919938411349285)])

In [19]:
#RelationRecord is data format in which apriori algorithm returns results
type(items_rules)

apyori.RelationRecord

In [20]:
items_rules[0]

frozenset({'frozen pizza', 'herb & pepper'})

In [21]:
items_rules[1]

0.015997866951073192

In [22]:
items_rules[2][0][2]

0.3234501347708895

In [23]:
items_rules[2][0][3]

3.2919938411349285

In [24]:
results_data = pd.DataFrame(0.0,columns = ['association rule','support','confidence','lift'],
                            index=range(0,20))

In [25]:
results_data

    association rule  support  confidence  lift
0                0.0      0.0         0.0   0.0
1                0.0      0.0         0.0   0.0
2                0.0      0.0         0.0   0.0
3                0.0      0.0         0.0   0.0
4                0.0      0.0         0.0   0.0
5                0.0      0.0         0.0   0.0
6                0.0      0.0         0.0   0.0
7                0.0      0.0         0.0   0.0
8                0.0      0.0         0.0   0.0
9                0.0      0.0         0.0   0.0
10               0.0      0.0         0.0   0.0
11               0.0      0.0         0.0   0.0
12               0.0      0.0         0.0   0.0
13               0.0      0.0         0.0   0.0
14               0.0      0.0         0.0   0.0
15               0.0      0.0         0.0   0.0
16               0.0      0.0         0.0   0.0
17               0.0      0.0         0.0   0.0
18               0.0      0.0         0.0   0.0
19               0.0      0.0         0.0   0.0

In [26]:
for z in range(len(result)):

    items_rules = result[z]
    results_data['association rule'][z] = list(items_rules[0])
    results_data['support'][z] = items_rules[1]
    results_data['confidence'][z] = items_rules[2][0][2]
    results_data['lift'][z] = items_rules[2][0][3]

In [27]:
results_data

                            association rule   support  confidence      lift
0              [herb & pepper, frozen pizza]  0.015998    0.323450  3.291994
1                  [frozen pizza, spaghetti]  0.039195    0.398915  2.291162
2                               [soup, milk]  0.015198    0.300792  2.321232
3                      [red wine, spaghetti]  0.010265    0.364929  2.095966
4           [chocolate, mineral water, milk]  0.013998    0.265823  2.051375
5               [chocolate, spaghetti, milk]  0.010932    0.278912  2.152382
6        [frozen pizza, mineral water, eggs]  0.010132    0.506667  2.125563
7        [frozen pizza, mineral water, milk]  0.011065    0.503030  2.110308
8   [frozen pizza, spaghetti, mineral water]  0.017064    0.416938  2.394681
9   [frozen vegetables, mineral water, milk]  0.011065    0.309701  2.389991
10          [mineral water, spaghetti, milk]  0.015731    0.263393  2.032623
11     [olive oil, mineral water, spaghetti]  0.010265    0.371981  2.136468
12                                       0.0  0.000000    0.000000  0.000000
13                                       0.0  0.000000    0.000000  0.000000
14                                       0.0  0.000000    0.000000  0.000000
15                                       0.0  0.000000    0.000000  0.000000
16                                       0.0  0.000000    0.000000  0.000000
17                                       0.0  0.000000    0.000000  0.000000
18                                       0.0  0.000000    0.000000  0.000000
19                                       0.0  0.000000    0.000000  0.000000